#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS ${ACCOUNT_DB_NAME}
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS ${TRAVEL_DB_NAME}
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON ${ACCOUNT_DB_NAME}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${TRAVEL_DB_NAME}.* TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;
EOSQL