# Generated by Django 6.0.7 on 2026-08-03 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0002_place_touristspot_source_id_alter_itinerary_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, default='신용카드 (**** **** **** 1234)', max_length=100)),
                ('status', models.CharField(choices=[('requested', '요청됨'), ('confirmed', '확정'), ('cancelled', '취소됨')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='travel.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_db_id', models.BigIntegerField()),
                ('package_id', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('option_date', models.DateField(blank=True, null=True)),
                ('option_people', models.PositiveSmallIntegerField(default=2)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservation.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_db_id', models.BigIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('option_date', models.DateField(blank=True, null=True)),
                ('option_people', models.PositiveSmallIntegerField(default=2)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'package_db_id')},
            },
        ),
    ]
