# Generated by Django 6.0.7 on 2026-07-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option_people',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
