# Generated by Django 6.0.7 on 2026-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_cartitem_option_date_cartitem_option_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='option_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='option_people',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
