# Generated by Django 6.0.7 on 2026-07-25 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='예: HIS001 (외부/시드 데이터 참조용 코드)', max_length=20, null=True, unique=True)),
                ('action', models.CharField(choices=[('visit', '방문'), ('chat_start', 'AI 대화 시작'), ('search', '검색'), ('view_package', '패키지 조회'), ('itinerary_save', '일정 저장'), ('reservation', '예약 요청')], default='visit', max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이용 기록',
                'verbose_name_plural': '이용 기록',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
