# Generated by Django 6.0.7 on 2026-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_budget',
            field=models.PositiveIntegerField(blank=True, help_text='1인당 선호 예산(원)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_style',
            field=models.CharField(blank=True, choices=[('family', '가족형'), ('healing', '힐링형'), ('activity', '액티비티형'), ('food', '맛집형')], max_length=20),
        ),
    ]
