# Generated by Django 6.0.7 on 2026-08-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_budget',
        ),
    ]
