# Generated by Django 6.0.7 on 2026-07-25 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('price_per_night', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('stay', '숙소'), ('car', '렌터카'), ('activity', '액티비티'), ('tour', '투어')], max_length=20)),
                ('style', models.CharField(blank=True, choices=[('family', '가족여행'), ('healing', '힐링여행'), ('activity', '액티비티'), ('food', '맛집여행')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveSmallIntegerField(default=1, help_text='상품 이용 일수')),
                ('region', models.CharField(blank=True, default='제주', max_length=50)),
                ('accommodation_included', models.BooleanField(default=False)),
                ('included_items', models.JSONField(blank=True, default=list, help_text='예: ["자차보험","내비게이션"]')),
                ('course', models.JSONField(blank=True, default=list, help_text='코스 설명 리스트')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, help_text='예: 흑돼지, 해산물, 카페', max_length=50)),
                ('price_range', models.CharField(blank=True, help_text='예: 1~2만원', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분된 태그 (예: 힐링,자연,포토스팟)', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제주 여행', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='예: "부모님과 함께"', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('companion_count', models.PositiveSmallIntegerField(default=1)),
                ('style', models.CharField(blank=True, choices=[('family', '가족여행'), ('healing', '힐링여행'), ('activity', '액티비티'), ('food', '맛집여행')], max_length=20)),
                ('budget_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('accommodation_cost', models.PositiveIntegerField(default=0, help_text='숙소')),
                ('transport_cost', models.PositiveIntegerField(default=0, help_text='렌터카/교통')),
                ('activity_cost', models.PositiveIntegerField(default=0, help_text='액티비티')),
                ('food_cost', models.PositiveIntegerField(default=0, help_text='식비')),
                ('etc_cost', models.PositiveIntegerField(default=0, help_text='기타')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('confirmed', '확정')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='공개 설정 (선택)')),
                ('share_token', models.UUIDField(blank=True, help_text='공유 링크용 토큰', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
                ('selected_package', models.BigIntegerField(blank=True, db_column='selected_package_id', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='1일차, 2일차 ...')),
                ('date', models.DateField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='travel.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('time', models.CharField(blank=True, help_text='예: "09:30"', max_length=10)),
                ('item_type', models.CharField(choices=[('spot', '관광지'), ('restaurant', '맛집'), ('accommodation', '숙소'), ('activity', '액티비티'), ('custom', '직접 추가')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.CharField(blank=True, help_text='이모지 썸네일 (예: 🌋)', max_length=10)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('memo', models.CharField(blank=True, help_text='직접 추가 일정용 메모', max_length=255)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodation')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.itineraryday')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.restaurant')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.touristspot')),
            ],
            options={
                'ordering': ['order', 'time'],
            },
        ),
    ]
