# Generated by Django 6.0.7 on 2026-08-03 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('content_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content_type_id', models.IntegerField()),
                ('lcls3_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('addr1', models.CharField(blank=True, max_length=500, null=True)),
                ('addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('area_code', models.IntegerField(blank=True, null=True)),
                ('sigungu_code', models.IntegerField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('location', models.BinaryField()),
                ('map_level', models.IntegerField(blank=True, null=True)),
                ('api_created_at', models.DateTimeField(blank=True, null=True)),
                ('api_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='touristspot',
            name='source_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
