# Generated by Django 6.0.7 on 2026-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place_alter_package_options_touristspot_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='companion_type',
            field=models.CharField(choices=[('solo', '혼자'), ('couple', '연인'), ('friend', '친구'), ('family', '가족')], default='solo', max_length=20),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transport',
            field=models.CharField(choices=[('car', '렌터카'), ('bus', '버스')], default='car', max_length=10),
        ),
    ]
