# Generated by Django 6.0.7 on 2026-08-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_itinerary_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
