# Generated by Django 6.0.7 on 2026-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="engine_state",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="Serialized itinerary engine state",
            ),
        ),
    ]