# Generated by Django 6.0.7 on 2026-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_itinerary_engine_state_alter_package_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='package',
            table='travel_packages',
        ),
    ]
