# Generated by Django 6.0.7 on 2026-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_itineraryitem_description_alter_package_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='썸네일 이미지 URL', max_length=1000),
        ),
    ]
