# Generated by Django 6.0.7 on 2026-08-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_itineraryitem_description_alter_package_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='transport_cost',
        ),
    ]
