# Generated by Django 6.0.7 on 2026-08-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_itineraryitem_thumbnail'),
        ('travel', '0008_remove_itinerary_transport_and_more'),
    ]

    operations = [
    ]
