# Generated by Django 6.0.7 on 2026-08-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_merge_20260806_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='accommodation_cost',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='activity_cost',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='etc_cost',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='food_cost',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, default='제주 여행', max_length=150),
        ),
    ]
