# Generated by Django 6.0.7 on 2026-08-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_itinerary_accommodation_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='budget_per_person',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='cost',
        ),
    ]
