# Generated by Django 6.0.7 on 2026-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_itinerary_budget_per_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='age_group',
            field=models.CharField(blank=True, help_text='여행 대표자의 나이대 (예: 10, 20, 30, 40, 50, 60)', max_length=10, null=True),
        ),
    ]
