# Generated by Django 6.0.7 on 2026-08-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_merge_20260806_1110'),
        ('travel', '0011_remove_itinerary_budget_per_person_and_more'),
    ]

    operations = [
    ]
