# Generated by Django 6.0.7 on 2026-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_itinerary_style_freetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='item_type',
            field=models.CharField(choices=[('spot', '관광지'), ('restaurant', '맛집'), ('accommodation', '숙소'), ('activity', '액티비티'), ('shopping', '쇼핑'), ('custom', '직접 추가')], default='custom', max_length=20),
        ),
    ]
