# Generated by Django 6.0.7 on 2026-08-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0013_remove_cross_database_package_fk"),
        ("travel", "0014_alter_itineraryitem_item_type"),
    ]

    operations = []
